sudo: required
language: perl
perl:
  - "5.18"                    # installs latest perl 5.18 (if not already available)

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto

install:
  - cpanm --notest --installdeps .

script:
  - perl Makefile.PL          # or Build.PL if it exists
  - make                      # or ./Build
  - prove -l -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
